// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mosquebookapi.Data;

namespace mosquebookapi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210415003109_seedingNewData")]
    partial class seedingNewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("mosquebookapi.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("Token")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("mosquebookapi.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("EventTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee48fa11-be9a-4885-a244-98a0aedfbea5"),
                            Date = new DateTime(2021, 4, 15, 0, 31, 9, 293, DateTimeKind.Local).AddTicks(2087),
                            Description = "",
                            EventTypeId = new Guid("d5d109a9-ac86-40ef-a783-b3c0b8fefaa1")
                        },
                        new
                        {
                            Id = new Guid("802e14d4-7c79-4740-aefc-6bf5b412129c"),
                            Date = new DateTime(2021, 4, 15, 0, 31, 9, 294, DateTimeKind.Local).AddTicks(162),
                            Description = "",
                            EventTypeId = new Guid("d5d109a9-ac86-40ef-a783-b4c0b8fefaa1")
                        },
                        new
                        {
                            Id = new Guid("513a6d9e-b4ee-4299-a945-241428be5114"),
                            Date = new DateTime(2021, 4, 15, 0, 31, 9, 294, DateTimeKind.Local).AddTicks(180),
                            Description = "",
                            EventTypeId = new Guid("d5d109a9-ac86-40ef-a783-b5c0b8fefaa1")
                        },
                        new
                        {
                            Id = new Guid("4ae8d4f8-7444-4aa5-9a80-af1c89f46805"),
                            Date = new DateTime(2021, 4, 15, 0, 31, 9, 294, DateTimeKind.Local).AddTicks(185),
                            Description = "",
                            EventTypeId = new Guid("d5d109a9-ac86-40ef-a783-b6c0b8fefaa1")
                        },
                        new
                        {
                            Id = new Guid("c23ed31c-5ddc-4993-8b39-7665f43b7fd9"),
                            Date = new DateTime(2021, 4, 15, 0, 31, 9, 294, DateTimeKind.Local).AddTicks(189),
                            Description = "",
                            EventTypeId = new Guid("d5d109a9-ac86-40ef-a783-b7c0b8fefaa1")
                        });
                });

            modelBuilder.Entity("mosquebookapi.Models.EventGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MaxPlaces")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a113557-d989-4243-af30-4d6906ce02de"),
                            EventId = new Guid("ee48fa11-be9a-4885-a244-98a0aedfbea5"),
                            MaxPlaces = 300,
                            Name = "Salat Fajr"
                        },
                        new
                        {
                            Id = new Guid("cf35efea-96a1-4f3a-943d-ae8389fb7337"),
                            EventId = new Guid("802e14d4-7c79-4740-aefc-6bf5b412129c"),
                            MaxPlaces = 10,
                            Name = "Salat Dohr"
                        },
                        new
                        {
                            Id = new Guid("2740bdfd-d621-4f42-9ae5-34e24ddc4e85"),
                            EventId = new Guid("513a6d9e-b4ee-4299-a945-241428be5114"),
                            MaxPlaces = 10,
                            Name = "Salat Asr"
                        },
                        new
                        {
                            Id = new Guid("a482283f-291a-43bd-8b88-6a4838e96998"),
                            EventId = new Guid("4ae8d4f8-7444-4aa5-9a80-af1c89f46805"),
                            MaxPlaces = 10,
                            Name = "Salat Maghreb"
                        },
                        new
                        {
                            Id = new Guid("b5d9b806-d791-440a-b773-8380b7d237bd"),
                            EventId = new Guid("c23ed31c-5ddc-4993-8b39-7665f43b7fd9"),
                            MaxPlaces = 10,
                            Name = "Salat Ishaa"
                        },
                        new
                        {
                            Id = new Guid("3be97c6d-7a78-44df-b1a7-2f7a035600c6"),
                            EventId = new Guid("c23ed31c-5ddc-4993-8b39-7665f43b7fd9"),
                            MaxPlaces = 10,
                            Name = "Tarawih group 1"
                        },
                        new
                        {
                            Id = new Guid("b450b7fa-7104-4cc1-9b4e-a15c639ca61e"),
                            EventId = new Guid("c23ed31c-5ddc-4993-8b39-7665f43b7fd9"),
                            MaxPlaces = 10,
                            Name = "Tarawih group 2"
                        });
                });

            modelBuilder.Entity("mosquebookapi.Models.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("MosqueId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.ToTable("EventType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5d109a9-ac86-40ef-a783-b3c0b8fefaa1"),
                            Description = "",
                            MosqueId = new Guid("1a82c06a-4986-4ed3-b1dd-05271b4931d8"),
                            Name = "Fajr"
                        },
                        new
                        {
                            Id = new Guid("d5d109a9-ac86-40ef-a783-b4c0b8fefaa1"),
                            Description = "",
                            MosqueId = new Guid("1a82c06a-4986-4ed3-b1dd-05271b4931d8"),
                            Name = "Dohr"
                        },
                        new
                        {
                            Id = new Guid("d5d109a9-ac86-40ef-a783-b5c0b8fefaa1"),
                            Description = "",
                            MosqueId = new Guid("1a82c06a-4986-4ed3-b1dd-05271b4931d8"),
                            Name = "Asr"
                        },
                        new
                        {
                            Id = new Guid("d5d109a9-ac86-40ef-a783-b6c0b8fefaa1"),
                            Description = "",
                            MosqueId = new Guid("1a82c06a-4986-4ed3-b1dd-05271b4931d8"),
                            Name = "Maghreb"
                        },
                        new
                        {
                            Id = new Guid("d5d109a9-ac86-40ef-a783-b7c0b8fefaa1"),
                            Description = "Please choose a group",
                            MosqueId = new Guid("1a82c06a-4986-4ed3-b1dd-05271b4931d8"),
                            Name = "Ishaa"
                        });
                });

            modelBuilder.Entity("mosquebookapi.Models.Mosque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Mosque");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a82c06a-4986-4ed3-b1dd-05271b4931d8"),
                            Address = "Neue Str. 3, 89077 Ulm",
                            Email = "AlSalam@gmail.com",
                            Name = "Al-Salam Moschee"
                        });
                });

            modelBuilder.Entity("mosquebookapi.Models.TemporaryAuthenticator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("Token")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("TemporaryAuthenticators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Token = new Guid("13b47836-12f0-4a17-a4d9-b9239e9ed64a")
                        });
                });

            modelBuilder.Entity("mosquebookapi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("mosquebookapi.Models.Appointment", b =>
                {
                    b.HasOne("mosquebookapi.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("mosquebookapi.Models.EventGroup", "Group")
                        .WithMany("Appointments")
                        .HasForeignKey("GroupId");

                    b.HasOne("mosquebookapi.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mosquebookapi.Models.Event", b =>
                {
                    b.HasOne("mosquebookapi.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventGroup", b =>
                {
                    b.HasOne("mosquebookapi.Models.Event", "Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventType", b =>
                {
                    b.HasOne("mosquebookapi.Models.Mosque", "Mosque")
                        .WithMany("Events")
                        .HasForeignKey("MosqueId");

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("mosquebookapi.Models.Event", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventGroup", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("mosquebookapi.Models.Mosque", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("mosquebookapi.Models.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
