// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mosquebookapi.Data;

namespace mosquebookapi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210423022208_GenerateDataModelWithData")]
    partial class GenerateDataModelWithData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("mosquebookapi.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("Token")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("mosquebookapi.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("EventTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MosqueId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("MosqueId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MaxPlaces")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("MosqueId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("mosquebookapi.Models.Mosque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Mosque");
                });

            modelBuilder.Entity("mosquebookapi.Models.TemporaryAuthenticator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("Token")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("TemporaryAuthenticators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Token = new Guid("08a2ddd2-a15d-4581-8eb8-8cca54cdf44f")
                        });
                });

            modelBuilder.Entity("mosquebookapi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("mosquebookapi.Models.Appointment", b =>
                {
                    b.HasOne("mosquebookapi.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("mosquebookapi.Models.EventGroup", "Group")
                        .WithMany("Appointments")
                        .HasForeignKey("GroupId");

                    b.HasOne("mosquebookapi.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mosquebookapi.Models.Event", b =>
                {
                    b.HasOne("mosquebookapi.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId");

                    b.HasOne("mosquebookapi.Models.Mosque", "Mosque")
                        .WithMany()
                        .HasForeignKey("MosqueId");

                    b.Navigation("EventType");

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventGroup", b =>
                {
                    b.HasOne("mosquebookapi.Models.Event", "Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventType", b =>
                {
                    b.HasOne("mosquebookapi.Models.Mosque", "Mosque")
                        .WithMany("Events")
                        .HasForeignKey("MosqueId");

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("mosquebookapi.Models.Event", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventGroup", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("mosquebookapi.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("mosquebookapi.Models.Mosque", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("mosquebookapi.Models.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
